import time
from collections import Counter, defaultdict
from functools import partial, cmp_to_key
from multiprocessing import Pool
from typing import IO, Any, BinaryIO
import regex as re
import os
from .common import split_by_pat, split_by_special_tokens

class Token:
    """A token with an associated byte value and token ID."""
    # pair_token indicates this token is generated by two other token combined together
    def __init__(self, token_id: int, value:bytes, child_pair=None) -> None:
        self.token_id = token_id
        self.bytes = value
        self.child_pair = child_pair
        
    def to_string(self):
        return self.bytes.decode("utf-8", errors="ignore")

def tokens_to_string(tokens: list[Token]) -> str:
    return "".join(token.to_string() for token in tokens)


def cmp_id_tuple(t_a, t_b, vocab):
    b_a = (vocab[t_a[0]], vocab[t_a[1]])
    b_b = (vocab[t_b[0]], vocab[t_b[1]])
    if b_a < b_b:
        return -1
    elif b_a == b_b:
        return 0
    else:
        return 1

def countPair(word: list[Token]):
    counter = Counter()
    for i in range(len(word)-1):
        counter[(word[i].token_id, word[i+1].token_id)] +=1
    
    return counter



def replace_new_token(word: list[Token], new_token) -> list[Token]:
    new_word = []
    curInd = 0
    while curInd < len(word):
        if curInd < len(word) -1 and (word[curInd].token_id, word[curInd +1].token_id) == new_token.child_pair:
            new_word.append(new_token)
            curInd += 2
        else:
            new_word.append(word[curInd])
            curInd +=1

    return new_word

class TokenGroupCounter:
    def __init__(self, token_groups: list[list[Token]], counts: list[int], vocab:dict[int, bytes] ) -> None:
        self.token_groups = token_groups
        self.vocab = vocab
        self.counts = counts
        self.len = len(counts)
        
        # pair_counter is token id  tuple and count
        self.pair_counter = Counter()
        # Location mapping is from  pair of token id to a set of token_groups
        self.location_mapping = defaultdict(set)
        self.merges = []
        
        for i in range(self.len):
            tokens_i = self.token_groups[i]
            cnt = self.counts[i]
            for j in range(len(tokens_i)-1):
                tup = (tokens_i[j].token_id, tokens_i[j+1].token_id)
                self.pair_counter[tup] += cnt
                self.location_mapping[tup].add(i)      
        
    def iterate(self):
        most_common_pairs = self.pair_counter.most_common()
        if len(most_common_pairs) == 0:
            return 
        
        top_frequency = most_common_pairs[0][1]
        top_pairs = [
          pair
          for pair, freq in most_common_pairs
          if freq == top_frequency
        ]

        comparator = partial(cmp_id_tuple, vocab = self.vocab)
        sorted_arr = sorted(top_pairs, key=cmp_to_key(comparator))
        merge_pair = sorted_arr[-1]
        #print(self.merges)
        self.merges.append((self.vocab[merge_pair[0]], self.vocab[merge_pair[1]]))
        new_token = Token(len(self.vocab), self.vocab[merge_pair[0]] + self.vocab[merge_pair[1]], child_pair = merge_pair)
        self.vocab[new_token.token_id] = new_token.bytes
        locations = self.location_mapping[merge_pair].copy()
        
        for location in locations:
            cnt = self.counts[location]
            before = self.token_groups[location]
            
            before_pair_counter = countPair(before)
            
            
            # need to implment replace_new_token
            after = replace_new_token(before, new_token)
            self.token_groups[location] =  after
            after_pair_counter = countPair(after)

            for pair in after_pair_counter:
                self.pair_counter[pair] += cnt * (after_pair_counter[pair] - before_pair_counter[pair])
                self.location_mapping[pair].add(location)                    
                    
            for pair in before_pair_counter:
                if pair not in after_pair_counter:
                    self.pair_counter[pair] -= cnt * before_pair_counter[pair]
                    self.location_mapping[pair].remove(location)


# input should be counter(str->int)
# output should be dict([list[token]], int))
def create_initial_state(vocab:dict[int, bytes], str_list: Counter[str]):
    res = []
    counts = []
    for s, cnt in str_list.items():
        s_byte = s.encode('utf-8')
        tokens = [Token(int(b), bytes([b])) for b in s_byte]
        res.append(tokens)
        counts.append(cnt)
        
    return TokenGroupCounter(res, counts, vocab)


def pre_processing(initial_str: str, special_tokens: list[str]) -> TokenGroupCounter:
    splited_1 = split_by_special_tokens(initial_str, special_tokens=special_tokens)
    splited_2 = split_by_pat(splited_1)
    return Counter(splited_2)


def find_chunk_boundaries(
    file: BinaryIO,
    desired_num_chunks: int,
    split_special_token: bytes,
) -> list[int]:
    """
    Chunk the file into parts that can be counted independently.
    May return fewer chunks if the boundaries end up overlapping.
    """
    assert isinstance(split_special_token, bytes), "Must represent special token as a bytestring"

    # Get total file size in bytes
    file.seek(0, os.SEEK_END)
    file_size = file.tell()
    file.seek(0)
    chunk_size = file_size // desired_num_chunks

    # Initial guesses for chunk boundary locations, uniformly spaced
    # Chunks start on previous index, don't include last index
    chunk_boundaries = [i * chunk_size for i in range(desired_num_chunks + 1)]
    chunk_boundaries[-1] = file_size

    mini_chunk_size = 4096  # Read ahead by 4k bytes at a time

    for bi in range(1, len(chunk_boundaries) - 1):
        initial_position = chunk_boundaries[bi]
        file.seek(initial_position)  # Start at boundary guess
        while True:
            mini_chunk = file.read(mini_chunk_size)  # Read a mini chunk

            # If EOF, this boundary should be at the end of the file
            if mini_chunk == b"":
                chunk_boundaries[bi] = file_size
                break

            # Find the special token in the mini chunk
            found_at = mini_chunk.find(split_special_token)
            if found_at != -1:
                chunk_boundaries[bi] = initial_position + found_at
                break
            initial_position += mini_chunk_size

    # Make sure all boundaries are unique, but might be fewer than desired_num_chunks
    return sorted(set(chunk_boundaries))


def run_train_bpe(
    input_path: str | os.PathLike,
    vocab_size: int,
    special_tokens: list[str],
    **kwargs,
) -> tuple[dict[int, bytes], list[tuple[bytes, bytes]]]:
    """Given the path to an input corpus, run train a BPE tokenizer and
    output its vocabulary and merges.

    Args:
        input_path (str | os.PathLike): Path to BPE tokenizer training data.
        vocab_size (int): Total number of items in the tokenizer's vocabulary (including special tokens).
        special_tokens (list[str]): A list of string special tokens to be added to the tokenizer vocabulary.
            These strings will never be split into multiple tokens, and will always be
            kept as a single token. If these special tokens occur in the `input_path`,
            they are treated as any other string.

    Returns:
        tuple[dict[int, bytes], list[tuple[bytes, bytes]]]:
            vocab:
                The trained tokenizer vocabulary, a mapping from int (token ID in the vocabulary)
                to bytes (token bytes)
            merges:
                BPE merges. Each list item is a tuple of bytes (<token1>, <token2>),
                representing that <token1> was merged with <token2>.
                Merges are ordered by order of creation.
    """
    with open(input_path, "rb") as f:
        num_processes = 8
        boundaries = find_chunk_boundaries(f, num_processes, b"<|endoftext|>")
        print("boundries ", boundaries)
        
        # The following is a serial implementation, but you can parallelize this
        # by sending each start/end pair to a set of processes.
        chunks = []
        for start, end in zip(boundaries[:-1], boundaries[1:]):
            f.seek(start)
            chunks.append(f.read(end - start).decode("utf-8").replace('\r\n', '\n').replace('\r', '\n'))
        worker = partial(pre_processing, special_tokens = special_tokens)
        with Pool(processes=num_processes) as pool:
            chunk_counts = pool.map(worker, chunks)
        
        total_counts = Counter()
        for c in chunk_counts:
            total_counts.update(c)
        
        initial_vocab = {i: bytes([i]) for i in range(256)}
        curLen = len(initial_vocab)
        for special_token in special_tokens:
            initial_vocab[curLen] = special_token.encode("utf-8")
            curLen+=1 

        state = create_initial_state(initial_vocab, total_counts)
        for i in range(vocab_size - curLen):
            state.iterate()

        #print(state.merges)
        # print(state.vocab)
        return (state.vocab, state.merges)